### PR TITLE
bz#2073297 - Sendgrid PVC utilization mails should contain PVC name

### PR DESCRIPTION
**Pull request by akshayashu**
Sendgrid Alerts only send emails/Alerts mentioning the PVC utilization, but the message must also contain the corresponding PVC name

### CODE REVIEW

**Comment by nb-ohad** [comment]
@akshayashu Why do you have 11 commits on this PR?

**Comment by akshayashu** [comment]
I pulled v2.0 for the latest commits, I think that is why all these commits are here too

**Comment by nb-ohad** [comment]
why v2.0 and not main?

**Comment by akshayashu** [comment]
I thought changes would first go into v2.0 and then collectively in main
I'll raise another PR

**Comment by nb-ohad** [comment]
All patches/features are going first into main, then we decided what and when to backport into versioned/release branches

**Pull request closed without merging**
