### PR TITLE
enabling network policy tests.

### PR DESCRIPTION
**Pull request by renan-campos**
Signed-off-by: Renan Campos <rcampos@redhat.com>

### CODE REVIEW

**Review by bindrad — APPROVED** [review]

**Comment by bindrad** [comment]
@renan-campos Should we add test for these scenarios?

- If aws-data configMap is not present then egress networkPolicy should not get created
- If aws-data configMap is updated then egress networkPolicy should get updated

**Review by leelavg — APPROVED** [review]

**Comment by nb-ohad** [comment]
@renan-campos Why are we skipping tests for non converged?

**Comment by rohan47** [comment]
> @renan-campos Why are we skipping tests for non converged?

@nb-ohad the code for skipping the tests for non converged are removed by this PR if I am not wrong

**Comment by nb-ohad** [comment]
@rohan47 I read the PR incorrectly. You are right

**Review by nb-ohad — APPROVED** [review]

**Pull request merged**
