### PR TITLE
remove redundant files from the repo

### PR DESCRIPTION
**Pull request by leelavg**
Signed-off-by: Leela Venkaiah G <lgangava@redhat.com>

### CODE REVIEW

**Comment by leelavg** [comment]
- pls don't mind as I need to send another PR for adding `config/manifests/bases/kustomization.yaml` in `.gitignore`

**Comment by nb-ohad** [comment]
@leelavg as of your last comment. What should we do with this PR?

**Comment by nb-ohad** [comment]
Ok, but what do you want to do with this one? close? review and merge?

**Comment by leelavg** [comment]
Maybe I informed my action too soon than necessary with that comment.

Need a review and merge for this PR.

**Pull request merged**
